version: "3.7"
services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - mariadb_volume:/data
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress_volume:/data
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: unless-stopped


volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aabdou/data
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aabdou/data
