version: "3.7"
services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    env_file:
      - ./.env
    restart: always

