version: "3.7"
services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_volume:/data
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    ports:
      - "9000:9000"
    build: ./requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress_volume:/data
    networks:
      - inception
    restart: unless-stopped

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped


volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aabdou/data
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aabdou/data


networks:
  inception:
    driver: bridge
